#!/usr/bin/env bash
# 文件职责：守住 reference 决策规则的高风险语义，防止旧坏味道回流。
# shellcheck disable=SC2016
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

fail() {
  printf '[FAIL] %s\n' "$*" >&2
  exit 1
}

assert_present() {
  local needle="$1"
  local file="$2"
  grep -Fq "$needle" "$file" || fail "missing required content in $file: $needle"
}

assert_absent() {
  local needle="$1"
  local file="$2"
  if grep -Fq "$needle" "$file"; then
    fail "forbidden legacy content in $file: $needle"
  fi
}

assert_regex() {
  local pattern="$1"
  local file="$2"
  grep -Eq "$pattern" "$file" || fail "missing required pattern in $file: $pattern"
}

COMPLETION="$ROOT/shared/reference/完成前验证.md"
DESIGN="$ROOT/shared/reference/设计原则.md"
TESTING="$ROOT/shared/reference/测试规范.md"
REUSE="$ROOT/shared/reference/代码复用.md"
FULLSTACK="$ROOT/shared/reference/全栈开发.md"
IMPACT="$ROOT/shared/reference/影响范围分析.md"
PERFORMANCE="$ROOT/shared/reference/性能效率.md"
TECH="$ROOT/shared/reference/技术选型.md"
SKILL_STANDARD="$ROOT/shared/reference/Skill质量标准.md"
SKILL_EFFECTIVENESS="$ROOT/shared/reference/Skill能力有效性标准.md"

test ! -f "$ROOT/shared/reference/agent-team-patterns.md" || fail "orphan TeamCreate reference should not return without an active consumer"
test ! -f "$ROOT/shared/reference/mcp-server开发.md" || fail "MCP server guidance should be owned by the mcp-builder skill, not duplicated as global reference"
test ! -f "$ROOT/shared/reference/影响文件格式.md" || fail "impact file format should be owned by impact analysis, not a standalone reference"

assert_present '重新执行原复现步骤或回归测试，记录预期结果出现且原错误不再出现；日志仅作为辅助证据' "$COMPLETION"
assert_present '基于影响范围运行对应回归；列出已覆盖对象、未覆盖风险、阻塞项或风险接受依据' "$COMPLETION"
assert_present '完成前验证用于裁决能否声明完成、上线或交付' "$COMPLETION"
assert_present '完成声明必须由本次成功标准、影响范围、当前工作区重新执行的验证命令或可复查记录共同支撑' "$COMPLETION"
assert_present '证据闭合的项才能汇报为已通过；证据缺口归入阻塞、缺陷处理、风险接受或待裁决' "$COMPLETION"
assert_present '## 裁决顺序' "$COMPLETION"
assert_present '定义验证面：从影响范围确认需要证明的目标行为、边界路径、失败路径、调用方、用户路径、业务不变量和同步项' "$COMPLETION"
assert_present '完成声明只采纳能直接证明目标行为、影响范围或质量约束的命令或记录' "$COMPLETION"
assert_present '完成汇报应逐项说明成功标准、达成状态、验证证据、未覆盖风险和下一步' "$COMPLETION"
assert_present '完成结论按证据范围命名：全部闭合时汇报完成；部分闭合时汇报已通过项、未闭合项和下一步' "$COMPLETION"
assert_present '完成汇报前，列出本次适用的验证项；每项记录命令与通过证据，或记录不适用原因和替代验证。' "$COMPLETION"
assert_absent '不用总结性“已完成”覆盖未闭合证据' "$COMPLETION"
assert_absent '日志/输出确认错误消失' "$COMPLETION"
assert_absent '任何一项没做' "$COMPLETION"

assert_present '架构设计要先看清需求背后的复杂度，再决定系统如何组织。' "$DESIGN"
assert_present '哪些复杂度需要通过验证、反馈和演进逐步收口？' "$DESIGN"
assert_present '复杂结构会增加理解成本、协作成本、变更成本和故障定位成本。' "$DESIGN"
assert_present '复杂需求要先拆成可理解、可取舍的架构问题，再进入技术方案。' "$DESIGN"
assert_present '比较过哪些备选方案，为什么没有选择？' "$DESIGN"
assert_present 'AUTO_DECISION 不授权真实引入或不可逆执行' "$TECH"
assert_absent 'Essential vs Accidental' "$DESIGN"
assert_absent 'Accidental Complexity' "$DESIGN"

assert_present '# 测试执行规范' "$TESTING"
assert_present '接到代码变更后，按顺序执行：明确测试依据，生成测试义务，选择测试层级' "$TESTING"
assert_present '将每条义务绑定到完成前重新执行的命令（fresh command）、测试结果、覆盖率报告或验证记录' "$TESTING"
assert_present '任一环节无法闭合时，完成结论进入阻塞、缺陷处理或用户明确风险接受' "$TESTING"
assert_present '每条测试义务都应写清依据来源、测试层级、命令或人工步骤、环境依赖、通过标准和证据位置' "$TESTING"
assert_present '依据来源' "$TESTING"
assert_present '测试层级' "$TESTING"
assert_present '命令或人工步骤' "$TESTING"
assert_present '环境依赖' "$TESTING"
assert_present '通过标准' "$TESTING"
assert_present '证据位置' "$TESTING"
assert_present '探索发现的风险应转成可追溯的测试义务后再作为交付条件' "$TESTING"
assert_present '无法绑定完成证据的测试义务不支撑完成、上线或客户交付' "$TESTING"
assert_present '测试依据来自本次成功标准、验收标准（AC）、影响范围分析、代码变更点、接口契约、业务不变量、历史缺陷和专项风险' "$TESTING"
assert_present '本次成功标准' "$TESTING"
assert_present '验收标准（AC）' "$TESTING"
assert_present '影响范围分析' "$TESTING"
assert_present '代码变更点' "$TESTING"
assert_present '接口契约' "$TESTING"
assert_present '业务不变量' "$TESTING"
assert_present '历史缺陷' "$TESTING"
assert_present '专项风险' "$TESTING"
assert_present '专项风险包括' "$TESTING"
assert_present '性能' "$TESTING"
assert_present '安全' "$TESTING"
assert_present '兼容性' "$TESTING"
assert_present '可访问性' "$TESTING"
assert_present '第三方依赖' "$TESTING"
assert_present '数据迁移风险' "$TESTING"
assert_present '每个依据都应转成可观察目标：输入或操作、前置状态、预期结果、边界条件、失败路径、真实依赖和影响对象' "$TESTING"
assert_present '输入或操作' "$TESTING"
assert_present '前置状态' "$TESTING"
assert_present '预期结果' "$TESTING"
assert_present '边界条件' "$TESTING"
assert_present '失败路径' "$TESTING"
assert_present '真实依赖' "$TESTING"
assert_present '影响对象' "$TESTING"
assert_present '先把“做成什么样算通过”补成可观察行为、边界条件、失败路径和真实依赖' "$TESTING"
assert_present '待裁决问题未关闭前，不给出完成结论' "$TESTING"
assert_present '新增或变更可观察行为时' "$TESTING"
assert_present '先形成会因目标缺失而失败的自动化测试' "$TESTING"
assert_present '仅当验证依赖一次性人工判断、外部环境不可控、缺少可调用入口或当前工具无法稳定复现时，才使用可复验的验收用例' "$TESTING"
assert_present '记录不自动化原因、输入、步骤、预期结果和验证方式' "$TESTING"
assert_present '写测试或实现新行为时，应先看到目标测试因行为缺失失败，再写最小实现使其通过' "$TESTING"
assert_present '项目已有覆盖率基线时，本次变更影响范围的覆盖率应保持或提升' "$TESTING"
assert_present '新增或变更的业务逻辑、分支判断和错误处理路径' "$TESTING"
assert_present '行覆盖率与分支覆盖率目标为 90% 以上' "$TESTING"
assert_present '单元测试应可独立运行并稳定复现，失败信息应定位到具体规则、分支或错误结果' "$TESTING"
assert_present '## 何时追加专项验证' "$TESTING"
assert_present '基础测试只能证明局部行为；当变更触达更高风险面时，要追加能证明真实结果的专项验证' "$TESTING"
assert_present '未触达的专项验证不作为交付条件，未触达原因应能从影响范围分析中说明' "$TESTING"
assert_present '涉及 DB 落库、缓存、文件、消息、外部调用或模块协作，就要用真实依赖、测试环境、本地容器或集成路径证明结果' "$TESTING"
assert_present '涉及接口契约，就要验证请求、响应、状态码、错误结构和关键副作用' "$TESTING"
assert_present '涉及鉴权、权限、敏感数据或跨租户数据，就要验证授权路径、拒绝路径、非法输入和敏感输出' "$TESTING"
assert_present 'Mock、Stub、Fake 用于单元测试中的依赖隔离和异常路径构造；它们证明替身条件下的本地行为，不替代真实依赖验收' "$TESTING"
assert_present '涉及高频查询、批处理、缓存策略、并发或资源占用，就要看性能指标或目标阈值' "$TESTING"
assert_present '涉及页面交互，就要验证键盘操作、焦点、语义、对比度和错误提示' "$TESTING"
assert_present '涉及第三方外部 API 且无稳定测试环境，就要用首次真实响应、录制回放、重录周期和格式校验证明可复验' "$TESTING"
assert_present '涉及数据迁移、数据格式、运行时或 API 版本，就要验证迁移结果、兼容范围和回滚准备' "$TESTING"
assert_present '最短真实流程指用户或调用方从真实入口完成本次成功标准的最少必要步骤' "$TESTING"
assert_present '主路径是目标用户或调用方完成核心成功标准的最短正常流程' "$TESTING"
assert_present '先用覆盖率发现未执行代码，再用行为断言、边界结果、失败路径和真实依赖证据证明测试有效性' "$TESTING"
assert_present '行为断言' "$TESTING"
assert_present '边界结果' "$TESTING"
assert_present '指标退化时，应说明原因、影响范围和用户明确的处理决定' "$TESTING"
assert_present '影响范围中需要回归的对象已验证，未覆盖项有风险说明、责任人和用户明确的处理决定' "$TESTING"
assert_present '先定严重程度，再定优先级；不得用优先级替代严重程度' "$TESTING"
assert_present '严重程度衡量问题本身的影响' "$TESTING"
assert_present '优先级衡量本次交付中应多快处理' "$TESTING"
assert_present '`S0 阻断`：核心流程不可用，数据丢失，权限/安全/资金/合规风险，线上高影响且无可接受绕行' "$TESTING"
assert_present '`P0 立即处理`：阻断验收、上线或客户交付，或线上高影响且无绕行' "$TESTING"
assert_present '缺陷记录应说明触发条件、实际结果、预期结果、影响范围、严重程度、优先级和复验方式' "$TESTING"
assert_present '触发条件' "$TESTING"
assert_present '实际结果' "$TESTING"
assert_present '严重程度' "$TESTING"
assert_present '优先级' "$TESTING"
assert_present '复验方式' "$TESTING"
assert_present '测试所需数据应在测试内创建或由 fixture 声明，并在执行后清理或隔离；测试不得依赖本地已有数据' "$TESTING"
assert_present '测试不得依赖本地已有数据' "$TESTING"
assert_present 'helper 只提取稳定重复的 setup，不隐藏关键输入、目标行为和断言' "$TESTING"
assert_present 'skip、xfail、flaky 结果、注释或删除的测试、无意义断言和复制实现逻辑的测试只作为风险信号，不作为通过证据' "$TESTING"
assert_present '证据未闭合的项目进入阻塞、风险或用户明确的处理决定' "$TESTING"
assert_present '覆盖率报告无法生成时，完成结论应说明工具缺口、已覆盖的测试义务和仍未量化的风险' "$TESTING"
assert_present '工具缺口' "$TESTING"
assert_present '已覆盖的测试义务' "$TESTING"
assert_present '仍未量化的风险' "$TESTING"
assert_present '新增或变更业务逻辑、分支判断和错误处理路径覆盖率达成目标' "$TESTING"
assert_present '只有以下条件全部成立，才能汇报完成、上线或客户交付' "$TESTING"
assert_present '已修复或取得用户明确风险接受' "$TESTING"
assert_present '完成前逐项绑定完成前重新执行的命令（fresh command）、测试结果、覆盖率报告或验证记录' "$TESTING"
assert_present '风险接受应记录接受人、接受范围、原因和后续处理方式' "$TESTING"
assert_absent '每个新函数都有测试' "$TESTING"
assert_absent '测试不是枚举测试类型' "$TESTING"

assert_present '复用要减少的是同一知识的重复维护，而不是单纯减少代码行数' "$REUSE"
assert_present '行数变少可以是好复用的结果，但不能作为复用是否成立的理由' "$REUSE"

assert_present '全栈任务先聚焦接口契约，再推进前后端实现。接口是前端和后端的衔接标准' "$FULLSTACK"
assert_present '请求方法、路径、参数、鉴权、幂等和分页规则清楚' "$FULLSTACK"
assert_present '响应字段、状态码、错误结构、空态和边界场景清楚' "$FULLSTACK"
assert_present '契约未冻结时，明确待决策项和阻塞范围，不把临时假设当成完成依据' "$FULLSTACK"

assert_present '代码符号、配置键、文档/规则条目、契约字段、脚本入口、数据表或 API 端点' "$IMPACT"
assert_present '列出调用方验证对象，并用回归结果证明行为未受影响' "$IMPACT"
assert_present '仅表示文件范围无交集；确认接口、数据、配置和运行时依赖无共享写入后，可并行' "$IMPACT"
assert_present '`impact_files` 记录本次变更影响的文件、路径或回归对象，以及它们被影响的原因' "$IMPACT"
assert_present '无额外影响：写 `[]`。写 `[]` 前必须已检查代码符号、配置/数据流、运行时依赖、用户路径/业务不变量和搜索盲区。' "$IMPACT"

assert_present '先用 profiling、日志或基准测试记录瓶颈与基线指标' "$PERFORMANCE"
assert_present '用同一场景对比命中率、延迟、内存、正确性回归和失效行为' "$PERFORMANCE"
assert_present '异步任务已定义超时、状态持久化、幂等和失败续跑策略。' "$PERFORMANCE"

assert_present '普通决策至少列 2 个候选；高影响低可逆决策列 3 个候选，少于 3 个时记录不可行原因' "$TECH"
assert_present '全局影响、低可逆或引入新技术栈时先向用户确认；仅用户已预授权的非交互流程可执行 AUTO_DECISION' "$TECH"

assert_present '好的 Skill 让 AI 按真实职责流程办成事' "$SKILL_STANDARD"
assert_present '任务成功标准的达成质量' "$SKILL_STANDARD"
assert_present '失败只能指向根因修复、明确阻塞，或在用户裁决后回退' "$SKILL_STANDARD"
assert_present '消费关系决定保留价值' "$SKILL_STANDARD"
assert_present '正文执行价值' "$SKILL_STANDARD"
assert_present '分析维度、消费者解释、历史说明、工具边界说明、写作约束和测试意图不得直接进入正文' "$SKILL_STANDARD"
assert_present '确定性、可枚举、可复验的事项交给脚本、schema、hook、gate 或测试' "$SKILL_STANDARD"
assert_present '触发者、执行入口、执行时机、失败结果' "$SKILL_STANDARD"
assert_present '质量审计要把发现直接落到修正动作' "$SKILL_STANDARD"
assert_present '流程归位：按理解问题、收集证据、形成判断、执行产出、验证交付的因果顺序组织步骤' "$SKILL_STANDARD"
assert_present '确定性落地：可枚举、可复验的规则有脚本、schema、hook、gate 或测试承载' "$SKILL_STANDARD"
assert_present '机器消费的形状由 schema 或模板承载，正文不重复定义大段合同' "$SKILL_STANDARD"
assert_present '缺少效果信号时，质量等级停在 L2/L3' "$SKILL_STANDARD"
assert_absent '硬失败' "$SKILL_STANDARD"
assert_absent '## Finding 规则' "$SKILL_STANDARD"
assert_absent '## 职责边界' "$SKILL_STANDARD"
assert_absent '本标准不负责' "$SKILL_STANDARD"
assert_absent '本文定义判断 Skill 质量的标准' "$SKILL_STANDARD"
assert_absent '标准是衡量“哪里有问题、为什么是问题、会怎样影响办事质量”的依据' "$SKILL_STANDARD"
assert_absent '不是审计流程、finding 格式、生命周期治理、hook 方案或脚本实现说明' "$SKILL_STANDARD"
assert_absent 'Skill生命周期管理.md' "$SKILL_STANDARD"

assert_present 'Skill 会占用触发入口、上下文预算和维护成本' "$SKILL_EFFECTIVENESS"
assert_present '只有持续带来专业流程收益或稳定偏好收益的 Skill，才值得保留' "$SKILL_EFFECTIVENESS"
assert_present '一个 Skill 值得存在，看七项' "$SKILL_EFFECTIVENESS"
assert_present '价值来源明确' "$SKILL_EFFECTIVENESS"
assert_present '职责真实' "$SKILL_EFFECTIVENESS"
assert_present '偏好稳定' "$SKILL_EFFECTIVENESS"
assert_present '## 价值来源' "$SKILL_EFFECTIVENESS"
assert_present '专业流程' "$SKILL_EFFECTIVENESS"
assert_present '稳定偏好' "$SKILL_EFFECTIVENESS"
assert_present '## 证据路径' "$SKILL_EFFECTIVENESS"
assert_present '`eval-type` 是评测字段，不是 Skill 本体类型' "$SKILL_EFFECTIVENESS"
assert_present '价值方向成立但证据不足时，信号为 `optimize`；价值来源缺失或反证成立时，信号为 `retire`' "$SKILL_EFFECTIVENESS"
assert_present '价值独立' "$SKILL_EFFECTIVENESS"
assert_present '成本可接受' "$SKILL_EFFECTIVENESS"
assert_present '反证清楚' "$SKILL_EFFECTIVENESS"
assert_present '经验证据' "$SKILL_EFFECTIVENESS"
assert_present '反证证据' "$SKILL_EFFECTIVENESS"
assert_present '评分量表为 1-5 分，5 分表示完全达成该维度' "$SKILL_EFFECTIVENESS"
assert_present '每次 retain 判断至少覆盖 3 个代表性样本' "$SKILL_EFFECTIVENESS"
assert_present '能力增益有基线对比或免除原因，偏好价值有用户确认或锚点保真证据' "$SKILL_EFFECTIVENESS"
assert_present '关键失败模式改善、上下文成本可接受' "$SKILL_EFFECTIVENESS"
assert_present '`retire` | 价值不足，进入移除讨论。' "$SKILL_EFFECTIVENESS"
assert_absent '一个 Skill 值得存在，至少应满足以下判断' "$SKILL_EFFECTIVENESS"
assert_absent '缺少这些证据时，结论为 `optimize`' "$SKILL_EFFECTIVENESS"
assert_absent '## Skill 类型' "$SKILL_EFFECTIVENESS"
assert_absent '## 职责边界' "$SKILL_EFFECTIVENESS"
assert_absent '本标准不负责' "$SKILL_EFFECTIVENESS"
assert_absent 'Skill生命周期管理.md' "$SKILL_EFFECTIVENESS"
assert_absent 'lifecycle_state":' "$SKILL_EFFECTIVENESS"
assert_absent 'Skill 质量标准的 D9' "$SKILL_EFFECTIVENESS"
assert_absent 'D9 存在合理性' "$SKILL_EFFECTIVENESS"

printf '[PASS] reference decision rules\n'
