#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=tests/lib/test-env.sh
. "$ROOT/tests/lib/test-env.sh"
ensure_test_rg
MATRIX="$ROOT/shared/skills/delivery-owner/scripts/phase3-grade-matrix.sh"
PM_SKILL="$ROOT/shared/skills/delivery-owner/SKILL.md"
PHASE3_DOC="$ROOT/shared/skills/delivery-owner/references/phase3-dispatch.md"
DISPATCH_GUIDE="$ROOT/shared/skills/delivery-owner/references/dispatch-guide.md"
CR_TEMPLATE="$ROOT/shared/skills/delivery-owner/references/templates/code-review-report-template.md"
QA_TEMPLATE="$ROOT/shared/skills/qa/references/templates/qa-report-template.md"
PM_QA_TEMPLATE="$ROOT/shared/skills/delivery-owner/references/templates/qa-report-template.md"
ACCEPT_TEMPLATE="$ROOT/shared/skills/delivery-owner/references/templates/acceptance-summary-template.md"
PLAN_TEMPLATE="$ROOT/shared/skills/tech-lead/references/templates/plan-template.md"
CHECK_SCRIPT="$ROOT/shared/skills/delivery-owner/scripts/completion_check.sh"
PRODUCT_CHECK="$ROOT/shared/skills/product/scripts/completion_check.sh"
TECH_LEAD_CHECK="$ROOT/shared/skills/tech-lead/scripts/completion_check.sh"
PILOT_EVIDENCE_DOC="$ROOT/docs/delivery-owner-role-20260411/pilot-evidence.md"
ROLLOUT_GATE_TEST="$ROOT/tests/test-delivery-owner-rollout-gate.sh"
REPLAY_GATE_TEST="$ROOT/tests/test-delivery-owner-replay-contract.sh"

fail() {
  printf '[FAIL] %s\n' "$*" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$MATRIX"

assert_lines() {
  local expected="$1"
  shift
  local got
  got="$(printf '%s\n' "$@")"
  [ "$got" = "$expected" ] || fail "unexpected matrix lines: expected [$expected], got [$got]"
}

assert_lines "REVIEW_A" "$(phase3_required_review_stages 轻量)"
assert_lines $'REVIEW_A\nREVIEW_B' "$(phase3_required_review_stages 标准)"
assert_lines $'REVIEW_A\nREVIEW_B' "$(phase3_required_review_stages 完整)"
assert_lines "QA_A" "$(phase3_required_qa_stages 轻量)"
assert_lines $'QA_A\nQA_C' "$(phase3_required_qa_stages 标准)"
assert_lines $'QA_A\nQA_B\nQA_C\nQA_D' "$(phase3_required_qa_stages 完整)"

phase3_optional_review_stage | grep -Fxq 'REVIEW_C' || fail "optional review stage should be REVIEW_C"
phase3_is_gate_stage REVIEW_A || fail "REVIEW_A should be a gate stage"
phase3_is_gate_stage QA_D || fail "QA_D should be a gate stage"
if phase3_is_gate_stage REVIEW_C; then
  fail "REVIEW_C should not be treated as a gate stage"
fi
phase3_is_non_waivable_stage REVIEW_A || fail "REVIEW_A should be non-waivable"
phase3_is_non_waivable_stage QA_A || fail "QA_A should be non-waivable"
if phase3_is_non_waivable_stage REVIEW_B; then
  fail "REVIEW_B should remain waivable"
fi
assert_lines "REVIEW_B" "$(phase3_escalation_review_stages INTERFACE_BREAK)"
assert_lines $'QA_B\nQA_C' "$(phase3_escalation_qa_stages INTERFACE_BREAK)"
assert_lines "REVIEW_B" "$(phase3_escalation_review_stages SHARED_FILES_EXPANSION)"
assert_lines "QA_C" "$(phase3_escalation_qa_stages SHARED_FILES_EXPANSION)"
assert_lines "REVIEW_B" "$(phase3_escalation_review_stages NON_CONVERGENCE)"
assert_lines $'QA_C\nQA_D' "$(phase3_escalation_qa_stages NON_CONVERGENCE)"
assert_lines "REVIEW_B" "$(phase3_escalation_review_stages BLOCKED_ACCUMULATION)"
assert_lines $'QA_C\nQA_D' "$(phase3_escalation_qa_stages BLOCKED_ACCUMULATION)"

grep -Fq -- "- 轻量：\`REVIEW_A + QA_A\`" "$PM_SKILL" || fail "delivery-owner skill missing lightweight matrix"
grep -Fq -- "- 标准：\`REVIEW_A + REVIEW_B + QA_A + QA_C\`" "$PM_SKILL" || fail "delivery-owner skill missing standard matrix"
grep -Fq -- "- 完整：\`REVIEW_A + REVIEW_B + QA_A + QA_B + QA_C + QA_D\`" "$PM_SKILL" || fail "delivery-owner skill missing full matrix"
grep -Fq -- "\`REVIEW_C\` 仅作为可选增强审查" "$PM_SKILL" || fail "delivery-owner skill missing REVIEW_C boundary"
grep -Fq 'Delivery Kickoff' "$PM_SKILL" || fail "delivery-owner skill missing delivery kickoff stage"
grep -Fq 'goal closure' "$PM_SKILL" || fail "delivery-owner skill missing goal closure requirement"
grep -Fq 'developer_report_ref' "$PM_SKILL" || fail "delivery-owner skill missing one-source evidence reference"
grep -Fq 'COMPLEXITY_DRIFT' "$PM_SKILL" || fail "delivery-owner skill missing deviation trigger vocabulary"

grep -Fq "| 轻量 | \`REVIEW_A\` | \`QA_A\` | 最小强门禁 |" "$PHASE3_DOC" || fail "phase3 dispatch missing lightweight row"
grep -Fq "| 标准 | \`REVIEW_A + REVIEW_B\` | \`QA_A + QA_C\` | 保留基础 AC + 回归防线 |" "$PHASE3_DOC" || fail "phase3 dispatch missing standard row"
grep -Fq "| 完整 | \`REVIEW_A + REVIEW_B\` | \`QA_A + QA_B + QA_C + QA_D\` | 覆盖完整用户旅程与探索性验证 |" "$PHASE3_DOC" || fail "phase3 dispatch missing full row"
grep -Fq "## 可选增强审查 — REVIEW_C（不纳入强门禁）" "$PHASE3_DOC" || fail "phase3 dispatch missing optional REVIEW_C section"
grep -Fq "## 动态升档规则" "$PHASE3_DOC" || fail "phase3 dispatch missing dynamic escalation section"
grep -Fq "## REPLAN 恢复协议" "$DISPATCH_GUIDE" || fail "dispatch guide missing REPLAN recovery protocol"
grep -Fq 'replan_request' "$DISPATCH_GUIDE" || fail "dispatch guide missing replan_request field"
grep -Fq 'batch_freeze_reason' "$DISPATCH_GUIDE" || fail "dispatch guide missing batch_freeze_reason field"
grep -Fq 'unlock_resolution' "$DISPATCH_GUIDE" || fail "dispatch guide missing unlock_resolution field"
grep -Fq 'plan_version_value' "$DISPATCH_GUIDE" || fail "dispatch guide missing plan_version_value contract"
grep -Fq '任何 residual_risk / waiver 都必须由用户显式确认' "$PHASE3_DOC" || fail "phase3 dispatch missing risk acceptance boundary"
grep -Fq "qa/references/templates/qa-report-template.md" "$PM_SKILL" || fail "delivery-owner skill should reference qa authoritative template"
grep -Fq "qa/references/templates/qa-report-template.md" "$PHASE3_DOC" || fail "phase3 dispatch should reference qa authoritative template"
grep -Fq 'test_cases_ref="' "$PHASE3_DOC" || fail "phase3 dispatch missing explicit test_cases_ref handoff"
grep -Fq 'test_cases_refs="' "$PHASE3_DOC" || fail "phase3 dispatch missing aggregated test_cases_refs handoff"
grep -Fq 'browser_required' "$PM_SKILL" || fail "delivery-owner skill missing browser_required dispatch rule"
grep -Fq 'browser_required' "$PHASE3_DOC" || fail "phase3 dispatch missing browser_required rule"
grep -Fq 'webapp-testing' "$PHASE3_DOC" || fail "phase3 dispatch missing browser testing capability note"
test ! -e "$PM_QA_TEMPLATE" || fail "delivery-owner should not own a duplicate qa template"

grep -Fq "强门禁仅跟踪 \`REVIEW_A / REVIEW_B\`。" "$CR_TEMPLATE" || fail "code-review template missing strong gate note"
grep -Fq '"review":{"REVIEW_A"' "$CR_TEMPLATE" || fail "code-review template metadata missing REVIEW_A"
grep -Fq '"REVIEW_B"' "$CR_TEMPLATE" || fail "code-review template metadata missing REVIEW_B"
if grep -Fq '"REVIEW_C"' "$CR_TEMPLATE"; then
  fail "code-review template metadata should not include REVIEW_C"
fi

grep -Fq "强门禁矩阵：轻量=\`QA_A\`；标准=\`QA_A + QA_C\`；完整=\`QA_A + QA_B + QA_C + QA_D\`。" "$QA_TEMPLATE" || fail "qa template missing gate matrix note"
grep -Fq "审查分级: {轻量, 标准, 完整, 未指定}" "$QA_TEMPLATE" || fail "qa template missing inherited grade option"
grep -Fq "执行范围: {full, 验证-A, 验证-B, 验证-C, 验证-D}" "$QA_TEMPLATE" || fail "qa template missing execution scope field"
grep -Fq "### QA_A UNIT 执行汇总" "$QA_TEMPLATE" || fail "qa template missing qa_a unit summary"
grep -Fq "### AC 追踪表" "$QA_TEMPLATE" || fail "qa template missing ac trace table"
grep -Fq "release_recommendation: {放行, 条件放行, 阻塞}" "$QA_TEMPLATE" || fail "qa template missing release recommendation"
grep -Fq "residual_risk:" "$QA_TEMPLATE" || fail "qa template missing residual risk field"
grep -Fq "uncovered_boundary:" "$QA_TEMPLATE" || fail "qa template missing uncovered boundary field"
grep -Fq "conditional_release_basis:" "$QA_TEMPLATE" || fail "qa template missing conditional release basis field"
grep -Fq "not_executed_reason" "$QA_TEMPLATE" || fail "qa template missing not executed reason field"
if grep -Fq "goal_closure_ref" "$QA_TEMPLATE"; then
  fail "qa template should not depend on acceptance-summary goal_closure_ref"
fi
grep -Fq "browser_tool:" "$QA_TEMPLATE" || fail "qa template missing browser_tool field"
grep -Fq "entry_url:" "$QA_TEMPLATE" || fail "qa template missing entry_url field"
grep -Fq "browser_evidence:" "$QA_TEMPLATE" || fail "qa template missing browser_evidence field"
grep -Fq "| Issue ID | 阶段 | severity | priority | impact_scope | user_impact | environment_or_build | regression_flag | temporary_workaround | owner_hint | 期望行为 | 实际行为 | 复现命令 |" "$QA_TEMPLATE" || fail "qa template missing defect triage fields"
grep -Fq '"grade":"{轻量, 标准, 完整, 未指定}"' "$QA_TEMPLATE" || fail "qa template metadata missing inherited grade option"
grep -Fq '"release_recommendation":"{放行, 条件放行, 阻塞}"' "$QA_TEMPLATE" || fail "qa template metadata missing release recommendation"
grep -Fq "QA_B（E2E 旅程） | {OK, ISSUE, N/A}（轻量/标准模式不执行）" "$QA_TEMPLATE" || fail "qa template missing standard N/A rule"
grep -Fq "QA_D（探索性测试） | {OK, ISSUE, N/A}（轻量/标准模式不执行）" "$QA_TEMPLATE" || fail "qa template missing full-only rule"

grep -Fq 'fresh proving command' "$PM_SKILL" || fail "delivery-owner skill missing fresh proving command requirement"
grep -Fq '完整输出' "$PM_SKILL" || fail "delivery-owner skill missing full output evidence requirement"
grep -Fq '不得用 Mock 验收替代' "$PM_SKILL" || fail "delivery-owner skill missing no-mock-final-acceptance rule"
grep -Fq 'proving_command' "$CR_TEMPLATE" || true
grep -Fq 'proving_command' "$PLAN_TEMPLATE" || fail "plan template should expose proving_command for downstream execution"
grep -Fq 'evidence_target' "$PLAN_TEMPLATE" || fail "plan template should expose evidence_target for downstream execution"
grep -Fq 'proving_command' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing proving_command field"
grep -Fq 'evidence_target' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing evidence_target field"
grep -Fq 'developer_report_ref' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing developer_report_ref field"
grep -Fq 'deviation_trigger' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing deviation trigger field"
grep -Fq 'control_action' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing control action field"
grep -Fq 'last_observed_at' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing runtime last_observed_at field"
grep -Fq 'runtime_snapshot' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing runtime snapshot field"
grep -Fq 'dispatch_mode' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing dispatch mode field"
grep -Fq 'plan_version_ref' "$ROOT/shared/skills/delivery-owner/references/templates/dev-report-template.md" || fail "dev-report template missing plan_version_ref field"
grep -Fq 'proving_command' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing proving_command cross-check note"
grep -Fq 'evidence_target' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing evidence_target cross-check note"
grep -Fq 'release_recommendation' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing release recommendation alignment"
grep -Fq 'QAR-' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing QAR issue ledger linkage"
grep -Fq 'kickoff_status:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing kickoff status"
grep -Fq 'plan_version_ref:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing plan_version_ref"
grep -Fq '## 最新状态摘要' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing latest runtime section"
grep -Fq 'last_observed_at:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing latest runtime timestamp"
grep -Fq 'runtime_snapshot:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing latest runtime snapshot"
grep -Fq 'current_plan_version_ref:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing current plan version ref"
grep -Fq 'preflight_evidence_ref:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing preflight evidence ref"
grep -Fq '## 目标闭环' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing goal closure section"
grep -Fq '| 目标 | goal_source_ref | execution_basis_ref | evidence_ref | result | remaining_gap |' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing goal closure columns"
grep -Fq 'sign_off_status:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing sign_off_status"
grep -Fq 'business_risk_acceptance_status:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing business_risk_acceptance_status"
grep -Fq 'risk_acceptance_basis:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing risk_acceptance_basis"
grep -Fq 'uncovered_boundary:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing uncovered_boundary"
grep -Fq 'conditional_release_basis:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing conditional_release_basis"
grep -Fq 'not_executed_reason:' "$ACCEPT_TEMPLATE" || fail "acceptance summary missing not_executed_reason"

[ -f "$PILOT_EVIDENCE_DOC" ] || fail "pilot evidence contract doc missing"
grep -Fq 'pilot_object:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing pilot_object field"
grep -Fq 'plan_version_ref:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing plan_version_ref field"
grep -Fq 'acceptance_summary_ref:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing acceptance_summary_ref field"
grep -Fq 'qa_report_ref:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing qa_report_ref field"
grep -Fq 'fresh_proving_output_ref:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing fresh_proving_output_ref field"
grep -Fq 'rubric_ref:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing rubric_ref field"
grep -Fq 'rubric_score:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing rubric_score field"
grep -Fq 'residual_risk_ref:' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing residual_risk_ref field"
grep -Fq '混版本' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing mixed-version rejection rule"
grep -Fq 'fresh_proving_output_ref` 必须落在真实 fresh proving output 所在锚点块内' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing anchored fresh proving rule"
grep -Fq 'rubric_ref` 必须落在冻结阈值所在锚点块内' "$PILOT_EVIDENCE_DOC" || fail "pilot evidence doc missing anchored rubric rule"

[ -f "$ROLLOUT_GATE_TEST" ] || fail "rollout gate test missing"
grep -Fq 'delivery-owner rollout gate contract' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing pass banner"
grep -Fq 'plan_version_ref' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing plan version check"
grep -Fq 'fresh_proving_output_ref' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing fresh proving output check"
grep -Fq 'Full rollout' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing full rollout threshold check"
grep -Fq 'residual_risk_ref' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing residual risk reference check"
grep -Fq 'dev-report plan_version_value' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing dev-report mixed-version check"
grep -Fq 'repo pilot qa-report 必须是 full 执行范围' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing repo pilot qa-report contract check"
grep -Fq 'repo pilot acceptance-summary 缺少章节' "$ROLLOUT_GATE_TEST" || fail "rollout gate test missing acceptance-summary contract check"
grep -Fq 'validate_rollout_gate "$ROOT/docs/delivery-owner-role-20260411/pilot-evidence.md"' "$ROLLOUT_GATE_TEST" || fail "rollout gate test should validate repo pilot evidence"

[ -f "$REPLAY_GATE_TEST" ] || fail "replay contract test missing"
grep -Fq 'delivery-owner replay contract' "$REPLAY_GATE_TEST" || fail "replay contract test missing pass banner"
grep -Fq 'readiness failure' "$REPLAY_GATE_TEST" || fail "replay contract missing readiness scenario"
grep -Fq 'execution drift and replan' "$REPLAY_GATE_TEST" || fail "replay contract missing drift/replan scenario"
grep -Fq 'quality escalation after risk increase' "$REPLAY_GATE_TEST" || fail "replay contract missing escalation scenario"
grep -Fq 'goal closure mismatch despite green gates' "$REPLAY_GATE_TEST" || fail "replay contract missing goal mismatch scenario"

grep -Fq "仅汇总强门禁阶段；可选增强 \`REVIEW_C\` 不进入此表。" "$ACCEPT_TEMPLATE" || fail "acceptance summary missing REVIEW_C exclusion note"
if rg -n 'REVIEW_C' "$ACCEPT_TEMPLATE" >/tmp/org_pm_phase3_accept_reviewc.out 2>&1; then
  line_count="$(wc -l < /tmp/org_pm_phase3_accept_reviewc.out | tr -d ' ')"
  [ "$line_count" -eq 1 ] || fail "acceptance summary should only mention REVIEW_C in exclusion note"
fi
if grep -Fq "{MAPPED, VERIFIED, BLOCKED}" "$ACCEPT_TEMPLATE"; then
  fail "acceptance summary should not advertise BLOCKED as a normal plan status"
fi
if grep -Fq -- "- BLOCKED:" "$ACCEPT_TEMPLATE"; then
  fail "acceptance summary should not document BLOCKED as a shippable plan state"
fi

grep -Fq -- "- 标准: \`REVIEW_A + REVIEW_B + QA_A + QA_C\`" "$PLAN_TEMPLATE" || fail "plan template missing standard gate matrix"
grep -Fq -- "- \`REVIEW_C\` 仅作为可选增强审查，不进入 \`/delivery-owner\` 的强门禁判定" "$PLAN_TEMPLATE" || fail "plan template missing REVIEW_C boundary"
grep -Fq "| CON-001 |" "$PLAN_TEMPLATE" || fail "plan template missing zero-padded constraint id example"
grep -Fq "| [TC-U1-001 / N/A] |" "$PLAN_TEMPLATE" || fail "plan template missing N/A test_ref branch"
if grep -Fq -- "- BLOCKED:" "$PLAN_TEMPLATE"; then
  fail "plan template should not instruct users to keep BLOCKED rows in final mapping"
fi
grep -Fq "禁止在最终表中保留 \`BLOCKED\` 行" "$PLAN_TEMPLATE" || fail "plan template should explain BLOCKED rows must be resolved before final output"

grep -Fq "source \"\$(cd \"\$(dirname \"\$0\")\" && pwd)/phase3-grade-matrix.sh\"" "$CHECK_SCRIPT" || fail "completion check should source phase3 matrix"
grep -Fq "review_stage_lines=\$(phase3_required_review_stages \"\$plan_grade\")" "$CHECK_SCRIPT" || fail "completion check should use review matrix function"
grep -Fq "qa_stage_lines=\$(phase3_required_qa_stages \"\$plan_grade\")" "$CHECK_SCRIPT" || fail "completion check should use qa matrix function"
grep -Fq "if ! phase3_is_gate_stage \"\$check_item\"; then" "$CHECK_SCRIPT" || fail "completion check should validate waiver stages from matrix"
grep -Fq 'proving_command' "$CHECK_SCRIPT" || fail "completion check should validate proving_command fields"
grep -Fq 'evidence_target' "$CHECK_SCRIPT" || fail "completion check should validate evidence_target fields"
grep -Fq 'developer_report_ref' "$CHECK_SCRIPT" || fail "completion check should validate developer report refs"
grep -Fq 'mock_boundary_note' "$CHECK_SCRIPT" || fail "completion check should validate mock boundary fields"
grep -Fq 'Fresh proving command' "$CHECK_SCRIPT" || fail "completion check should require fresh proving command output section"
grep -Fq 'release_recommendation' "$CHECK_SCRIPT" || fail "completion check should validate release recommendation alignment"
grep -Fq 'residual_risk' "$CHECK_SCRIPT" || fail "completion check should validate residual risk"
grep -Fq 'business_risk_acceptance_status' "$CHECK_SCRIPT" || fail "completion check should validate business risk acceptance status"
grep -Fq 'risk_acceptance_basis' "$CHECK_SCRIPT" || fail "completion check should validate risk acceptance basis"
grep -Fq 'has_runtime_anchor_ref' "$CHECK_SCRIPT" || fail "completion check should validate runtime anchor refs"
grep -Fq 'dispatch_mode' "$CHECK_SCRIPT" || fail "completion check should validate dispatch mode"
grep -Fq 'current_plan_version_ref' "$CHECK_SCRIPT" || fail "completion check should validate acceptance current plan version ref"
grep -Fq 'validate_anchored_refs_exist "$dev_plan_version_ref"' "$CHECK_SCRIPT" || fail "completion check should validate dev plan version anchor existence"
grep -Fq 'validate_anchored_refs_exist "$report_evidence_target"' "$CHECK_SCRIPT" || fail "completion check should validate evidence_target anchor existence"
grep -Fq 'validate_anchored_refs_exist "$developer_report_ref"' "$CHECK_SCRIPT" || fail "completion check should validate developer_report_ref anchor existence"
grep -Fq 'validate_anchored_refs_exist "$preflight_evidence_ref"' "$CHECK_SCRIPT" || fail "completion check should validate preflight evidence anchor existence"
grep -Fq 'goal_source_refs_are_allowed' "$CHECK_SCRIPT" || fail "completion check should validate allowed goal source refs"
grep -Fq 'execution_basis_refs_are_allowed' "$CHECK_SCRIPT" || fail "completion check should validate allowed execution basis refs"
grep -Fq 'validate_anchored_refs_exist "$goal_source_ref"' "$CHECK_SCRIPT" || fail "completion check should validate goal_source_ref anchor existence"
grep -Fq 'validate_anchored_refs_exist "$execution_basis_ref"' "$CHECK_SCRIPT" || fail "completion check should validate execution_basis_ref anchor existence"
grep -Fq 'validate_anchored_refs_exist "$evidence"' "$CHECK_SCRIPT" || fail "completion check should validate goal closure evidence anchor existence"
grep -Fq 'last_observed_at' "$CHECK_SCRIPT" || fail "completion check should validate latest runtime timestamps"
grep -Fq 'release_is_more_lenient_than' "$CHECK_SCRIPT" || fail "completion check should enforce no-wider-than-QA acceptance release"
grep -Fq 'QAR-' "$CHECK_SCRIPT" || fail "completion check should validate qa issue ledger linkage"
grep -Fq 'kickoff_status' "$CHECK_SCRIPT" || fail "completion check should validate kickoff status"
grep -Fq 'preflight_evidence_ref' "$CHECK_SCRIPT" || fail "completion check should validate preflight evidence ref"
grep -Fq 'extract_goal_closure_rows' "$CHECK_SCRIPT" || fail "completion check should validate goal closure rows"
grep -Fq 'D-PRE' "$CHECK_SCRIPT" || fail "completion check should keep preflight gate"
grep -Fq "^CON-[0-9]{3,}$" "$PRODUCT_CHECK" || fail "product constraint id regex should require zero-padded ids"
grep -Fq "^CON-[0-9]{3,}$" "$TECH_LEAD_CHECK" || fail "tech-lead constraint id regex should require zero-padded ids"
grep -Fq "^CON-[0-9]{3,}$" "$CHECK_SCRIPT" || fail "delivery-owner constraint id regex should require zero-padded ids everywhere"
grep -Fq "normalized_test_ref" "$TECH_LEAD_CHECK" || fail "tech-lead should normalize test_ref before validation"
grep -Fq "normalized_test_ref" "$CHECK_SCRIPT" || fail "delivery-owner should normalize test_ref before validation"
grep -Fq "grep -qiE '^N/?A$'" "$TECH_LEAD_CHECK" || fail "tech-lead should allow N/A test_ref in constraint mapping"
grep -Fq "grep -qiE '^N/?A$'" "$CHECK_SCRIPT" || fail "delivery-owner should allow N/A test_ref in constraint mapping"
if rg -n '\bmapfile\b' "$CHECK_SCRIPT" >/tmp/org_pm_phase3_mapfile.out 2>&1; then
  cat /tmp/org_pm_phase3_mapfile.out >&2
  fail "completion check must stay compatible with bash 3.2 and should not use mapfile"
fi

grep -Fq '允许出现额外系统 skills' "$PM_SKILL" || fail "delivery-owner skill missing extra system skills note"
grep -Fq '允许存在额外系统 skills' "$PHASE3_DOC" || fail "phase3 dispatch missing extra system skills note"
grep -Fq '计划模式' "$PM_SKILL" || fail "delivery-owner skill missing planning mode support"
grep -Fq '探索优先' "$PM_SKILL" || fail "delivery-owner skill missing exploration-first mode"
grep -Fq "等待刷新后的 \`plan.md\`" "$PM_SKILL" || fail "delivery-owner skill missing replan pause rule"
grep -Fq '## 计划模式' "$PLAN_TEMPLATE" || fail "plan template missing planning mode section"
grep -Fq '## 再计划与解锁规则' "$PLAN_TEMPLATE" || fail "plan template missing replan section"
grep -Fq '## 计划修订记录' "$PLAN_TEMPLATE" || fail "plan template missing plan revision section"
grep -Fq '计划模式' "$TECH_LEAD_CHECK" || fail "tech-lead completion check missing planning mode validation"
grep -Fq '再计划与解锁规则' "$TECH_LEAD_CHECK" || fail "tech-lead completion check missing replan validation"
grep -Fq 'task_type' "$TECH_LEAD_CHECK" || fail "tech-lead completion check missing task_type validation"
grep -Fq 'unlock_condition' "$TECH_LEAD_CHECK" || fail "tech-lead completion check missing unlock condition validation"
grep -Fq 'QAR-' "$ROOT/shared/skills/delivery-owner/references/templates/waivers-template.md" || fail "waivers template missing QAR linkage"
grep -Fq '补偿控制' "$ROOT/shared/skills/delivery-owner/references/templates/waivers-template.md" || fail "waivers template missing compensating control field"
grep -Fq '到期时间' "$ROOT/shared/skills/delivery-owner/references/templates/waivers-template.md" || fail "waivers template missing expiry field"

echo "[PASS] delivery-owner phase3 contract"
